### ISSUE TITLE
Cambio en función de cargar modelos en bmdbutils para que se ajuste a cambio de permisos

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-db-utils#8]
Hacer el ajuste de tal manera que la carga de modelos de **bmdbutils** siga funcionando dados los cambios en los permisos y definición de reglas de acceso (En esta [tarea](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/gh/pem-humboldt/biomodelos-scrum/122)).

Para esto se debe tener en cuenta agregar los permisos de lectura para el usuario de biomodelos una vez se han cargados los modelos, esto aplica para los nuevos workspaces, que en la práctica son nueves especies.

Adicionalmente, cambiar el orden de las opciones de instalación, de manera que usando conda sea la primera opción, se puede agregar una explicación o enunciado si se considera útil

**Comment by erikasv** [comment]
@cazapatamar esta tarea acaba de cobrar prioridad altísima, es necesaria para  la carga de modelos de aves

**Comment by erikasv** [comment]
Ya quedó ajustada, de acuerdo a la reunión de hoy depronto no es necesaria como dependencia, pero sí hay que subirle la prioridad

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-db-utils/8?planning-poker) with Zenhub @cazapatamar
